swagger: "2.0"
info:
  title: "MockAPI Test API"
  description: "API for testing IICS REST v2 connection"
  version: "1.0.0"
host: "65a8ca65219bfa37186795e7.mockapi.io"
basePath: "/"
schemes:
  - "https"
paths:
  /api/test_iics:
    post:
      summary: "Test IICS Connection"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            type: "object"
            properties:
              content:
                type: "string"
                example: "Check out mockapi.io"
            required:
              - "content"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            properties:
              id:
                type: "string"
              content:
                type: "string"
              createdAt:
                type: "string"
